webapp/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    #/music/
    url(r'^$',views.IndexView.as_view(),name="index"),

    #/music/#id
    url(r'^(?P<artist>.+)/(?P<album_title>.+)/$',views.DetailView.as_view(), name="details"),

    #music/album/add
    url(r'album/add$', views.AlbumCreate.as_view(),name='album-add'),

    url(r'^(?P<artist>.+)/(?P<album_title>.+)/update/$', views.AlbumUpdate.as_view(),name='album-update'),

    url(r'^(?P<artist>.+)/(?P<album_title>.+)/delete/$', views.AlbumDelete.as_view(),name='album-delete')

]

webapp/webapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/',include('music.urls')),
    url(r'',include('music.urls'))
]

webapp/music/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)


    def get_absolute_url(self):
        return reverse('music:details',kwargs={'artist':self.artist, 'album_title':self.album_title})

    # string representation of object
    def __str__(self):
        return self.album_title + " - "+self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

webapp/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album
from django.core.urlresolvers import reverse_lazy


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'
    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'

    def get_object(self,queryset=None):
        artist = self.kwargs['artist']
        album_title = self.kwargs['album_title']
        return Album.objects.all().filter(artist=artist).filter(album_title=album_title)[0]

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

webapp/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block body %}
<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'music/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>
{% endblock %}

webapp/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Music App {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css'%}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Metal+Mania' rel='stylesheet' type='text/css'>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">Home</a>
            </div>
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="{% url 'music:index'%}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                            Albums
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'music:index'%}">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                            Songs
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                   <div class="form-group">
                       <input type="text" class="form-control" name="q" value="">
                   </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                            Add Album
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                            Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block body%}

    {% endblock %}
</body>
</html>

webapp/music/templates/music/details.html
{% extends 'music/base.html' %}
{% block title%} {{album.album_title}} {% endblock %}
{% block body %}
    {% if error_msg %}
        <p>Sumfink gouent ronk</p>
    {% endif %}
    <p>Details of {{album.album_title}}</p>
    <ul>
        <li>{{album.artist}}</li>
        <li>{{album.genre}}</li>
        <img src="{{album.album_logo}}">
    </ul>
    <p>Songs of the album {{album.album_title}}</p>
    <form action="#" method="post">
        {% csrf_token %}
        <ul>
            {% for song in album.song_set.all %}
            <li>{{song.song_title}} <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}">
            {% if song.is_favorite%}
                <img src="https://cdn3.iconfinder.com/data/icons/freeapplication/png/24x24/Favourites.png"/>
            {% endif %}
            </li>
            {% endfor %}
        </ul><input type="submit" value="Favorite">
    </form>
{% endblock %}

webapp/music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

webapp/music/templates/music/index.html
{% extends 'music/base.html'%}
{% block body %}
    {% if all_albums %}
        <ul>
            {% for album in all_albums %}
                <li><a href="{% url 'music:details' artist=album.artist album_title=album.album_title %}">{{album.album_title}}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No albums added yet</p>
    {% endif %}
{% endblock %}