dow/dow/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('work_as.urls'))
]

dow/work_as/urls.py
from django.conf.urls import url
from . import views

app_name = 'work_as'

urlpatterns = [
    url(r'^$',views.login,name="login"),
    url(r'^login',views.login,name="login"),
    url(r'^main',views.main.as_view(),name="main"),
    url(r'^parts',views.parts.as_view(),name="parts"),
    url(r'^newPart',views.createPart.as_view(),name="newPart"),
    url(r'search',views.search,name="search"),
    url(r'details/part/(?P<part_code>.+)',views.partDetail.as_view(),name="partDetail")
    ]

dow/work_as/models.py
from __future__ import unicode_literals
from django.core.validators import MinValueValidator
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=30)
    is_manager = models.BooleanField()

    def __str__(self):
        return self.name+" "+self.surname


class Note(models.Model):
    poster = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=100)
    color = models.CharField(max_length=6)

    def __str__(self):
        return self.text+" "+self.poster.surname


class Storage(models.Model):
    site = models.CharField(max_length=15)
    location = models.CharField(max_length=5)

    def __str__(self):
        return self.site+" "+self.location

    class Meta:
        unique_together = ('site', 'location',)


class Part(models.Model):
    code = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=50)
    price = models.FloatField(validators=[MinValueValidator(0)])
    quantity = models.IntegerField(validators=[MinValueValidator(0)])
    storage = models.ManyToManyField(Storage)

    def get_absolute_url(self):
        return reverse('work_as:newPart')

    def __str__(self):
        return self.code+" "+self.description

dow/work_as/views.py
from django.shortcuts import render,render_to_response
from django.views import generic
from .models import Note,Part
from django.http import HttpResponse
import json
# Create your views here.

def login(request):
    return render(request,'work_as/login.html',{})


class main(generic.ListView):
    template_name = 'work_as/main.html'
    context_object_name = 'all_notes'
    model = Note

class parts(generic.ListView):
    template_name = 'work_as/parts.html'
    context_object_name = 'all_parts'
    model = Part

class createPart(generic.CreateView):
    model = Part
    fields = [
        'code',
        'description',
        'price',
        'quantity',
        'storage'
    ]
    def form_valid(self, form):
        self.object = form.save()
        return HttpResponse("")

    def form_invalid(self, form):
        return render(self.request,"work_as/form-template.html",{'form':form},status=400)

class partDetail(generic.DetailView):
    context_object_name = 'part'
    template_name = 'work_as/partDetail.html'
    model = Part

    def get_object(self,queryset=None):
        return Part.objects.all().filter(code=self.kwargs['part_code'])[0]

def search(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        parts = Part.objects.filter(code__icontains = q )[:20]
        results = []
        for part in parts:
            part_json = {}
            part_json['id'] = part.code
            part_json['label'] = part.code
            part_json['value'] = part.code
            results.append(part_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

dow/work_as/templates/work_as/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}Work Assistant{% endblock %}</title>
    {% load staticfiles %}
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0-rc.2/jquery-ui.min.js"></script>
    <link href = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel = "stylesheet">
    <script src = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'work_as/style.css'%}">
    <script src ="{% static 'work_as/search.js' %}"></script>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    {% block head %}
    {% endblock %}
</head>
<body class="body">
<div class="container">
    <div class="row">
        <div class="col-md-4">
	  <!-- navigation bar -->
	  <nav class = "navbar navbar-inverse navbar-fixed-top" role = "navigation">
		<div class="container-fluid">
            <div class = "navbar-header">
			    <a class = "navbar-brand" href = "{% url 'work_as:main' %}">Main</a>
                <button class="nav navbar-nav navbar-toggle navbar-header" data-toggle="collapse" data-target=".navHeaderCollapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
		    </div>
            <div class="collapse navbar-collapse navHeaderCollapse">
                <ul class = "nav navbar-nav">
                    <li class = "dropdown">
                    <a href = "" class = "dropdown-toggle" data-toggle = "dropdown">
                    Work Orders
                        <b class = "caret"></b>
                    </a>
                        <ul class = "dropdown-menu">
                            <li><a href = "">New</a></li>
                            <li><a href = "">Close</a></li>
                        </ul>
                    </li>
                    </ul>
                <ul class = "nav navbar-nav">
                    <li class = "dropdown">
                    <a href = "" class = "dropdown-toggle" data-toggle = "dropdown">
                    Parts
                        <b class = "caret"></b>
                    </a>
                        <ul class = "dropdown-menu">
                            <li><a href = "{% url 'work_as:newPart' %}">New</a></li>
                            <li><a href = "{% url 'work_as:parts' %}">View all</a></li>
                        </ul>
                    </li>
                    </ul>
                <form class="nav navbar-nav navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search" name="q" id="q">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Logout user <span class="glyphicon glyphicon-off"></span></a></li>
                    <li><span>&nbsp;&nbsp;</span></li>
                </ul>
            </div>
        </div>
      </nav>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row text-center">
        <div class="col-sm-12">
            <h1 class="">{% block page_title%}{% endblock %}</h1>
        </div>
    </div>
</div>
{% block body %}
{% endblock %}
</body>
</html>

dow/work_as/templates/work_as/form-template.html
{% for field in form %}
    <div class="form-group row">
        <div class="col-xs-6 text-right">
            <label class="control-label text-right">{{ field.label_tag }}</label>
        </div>
        <div class="col-xs-6 text-left">
            {{field}}
            <span class="text-danger small">{{field.errors}}</span>
        </div>
    </div>
{% endfor %}

dow/work_as/templates/work_as/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Work assistant</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'work_as/style.css'%}">
    <link href = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel = "stylesheet">
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
  </head>
  <body class="body">
	<div class="container">
	<div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please login to continue</h3>
                </div>
                <div class="panel-body">
                    <form role="form">
                        <fieldset>
                            <div class="form-group input-group">
								<span class="input-group-addon">
									<i class="glyphicon glyphicon-user"></i>
								</span>
                                <input class="form-control" placeholder="Username" name="email" type="text" autofocus required>
                            </div>
                            <div class="form-group input-group">
								<span class="input-group-addon">
									<i class="glyphicon glyphicon-lock"></i>
								</span>
                                <input class="form-control" placeholder="Password" name="password" type="password" required>
                            </div>
                            <button type="button" class="btn btn-success btn-block">Login</button>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

  </body>
</html>

dow/work_as/templates/work_as/main.html
{% extends 'work_as/base.html'%}
{% load staticfiles %}
{% block title %}
Main page
{% endblock %}
{% block head %}
    <script src="{% static 'work_as/tilt.js' %}"></script>
{% endblock %}
{% block page_title %}Manager's Notes{% endblock %}

{% block body %}
    {% if all_notes %}
    <div class="container">
        <div class="row text-center">
            <div class="col-xs-12">
                <div class="row">
        {% for note in all_notes %}
                <div class="col-md-4 text-center">
                    <blockquote class="quote-box shadow" style="background-color:#{{note.color}}">
                        <p class="quotation-mark hand-font">“</p>
                        <p class="quote-text">{{ note.text }}</p>
                        <div class="blog-post-actions">
                            <p class="blog-post-bottom pull-right hand-font">{{ note.poster.name}} {{note.poster.surname }}</p>
                        </div>
                    </blockquote>
                </div>
    {% endfor %}
            </div>
        </div>
    </div>
    </div>

    {% else %}
    <p>No notes added yet</p>
    {% endif %}
</div>
{% endblock %}
kquote>-->

dow/work_as/templates/work_as/partDetail.html
{% extends 'work_as/base.html' %}
{% load staticfiles %}
{% block title %}
Part details
{% endblock %}
{% block page_title %}Detail view{% endblock %}
{% block body %}
<br>
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})

</script>
<div class="container">
        <div class="row text-center">
            <div class="col-xs-6 col-xs-offset-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>Code: {{ part.code }}</p>
                        <p>Description: {{ part.description }}</p>
                        <p>Quantity: {{ part.quantity }}</p>
                        <p>Price: {{ part.price }}</p>
                        <p>Stored in:
                            {% for location in part.storage.all %}
                            <li>{{location}}</li>
                            {% endfor %}
                        </p>
                    </div>
                </div>
                <button type="button" class="btn" data-toggle="tooltip" data-placement="bottom" title="Edit">
                    <span class="glyphicon glyphicon-wrench"></span>
                </button>&nbsp;
                <button type="button" class="btn btn-danger" data-toggle="tooltip" data-placement="bottom" title="Delete">
                    <span class="glyphicon glyphicon-trash" ></span>
                </button>&nbsp;
            </div>
        </div>
</div>
{% endblock %}

dow/work_as/templates/work_as/part_form.html
{% extends 'work_as/base.html' %}
{% load staticfiles %}
{% block title %}New part {% endblock %}
{% block head %}
<script type="text/javascript" src="{% static 'work_as/submit.js'%}"></script>
{% endblock%}
{% block page_title %} New part {% endblock %}
{% block body %}
<br>
<div class="container-fluid">
        <div class="panel panel-default container success">
            <div class="panel panel-body">
                <form id="submit-form" class="form-horizontal" action="" method="post">
                    {% csrf_token %}
                    <div class="row" id="form-content">
                        {% include 'work_as/form-template.html'%}
                    </div>
                    <div class="form-group text-center">
                        <button id="submit_btn" class="btn btn-success">Submit</button>
                        <!--<input type="button" id="test" value="Test me">-->
                        <br>
                        <br>
                        <div id="message">
                        </div>
                    </div>
                </form>
            </div>
        </div>
</div>
{% endblock %}

dow/work_as/templates/work_as/parts.html
{% extends 'work_as/base.html' %}
{% load staticfiles %}
{% block title %}
Parts
{% endblock %}
{% block page_title %}Parts{% endblock %}
{% block body %}
<br>
<div class="container">
    {% if all_parts %}
    <table class="table table-hover table-striped table-fixed">
        <thead>
        <tr>
            <th>Code</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Location</th>
        </tr>
        </thead>
        {% for part in all_parts %}
            <tr class="trlink" data-url="{% url 'work_as:main'%}" rowspan="{{part.storage.all|length}}">
                <td id="valigned">{{part.code}}</td>
                <td id="valigned">{{part.description}}</td>
                <td id="valigned">{{part.quantity}}</td>
                <td id="valigned">{{part.price}}</td>
                <td id="valigned">
                {% for location in part.storage.all %}
                {{location}}<br>
                {% endfor %}
                </td>
            </tr>
        {% endfor %}
  </table>
    {% else %}
    <p>No parts added yet!</p>
    {% endif %}
</div>
{% endblock %}

dow/work_as/templates/work_as/updatePart.html
{% extends 'work_as/base.html' %}
{% load staticfiles %}
{% block title %}
Update part
{% endblock %}
{% block page_title %}Update part{% endblock %}
{% block body %}
{% endblock %}